version: '3'

services:
  nginx:
    image: nginx
    container_name: url-dryer-nginx
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - url-dryer

  url-dryer:
    build: .
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - PORT=3000
    expose:
      - "3000"
    volumes:
      - .:/usr/src/app
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis
    container_name: url-dryer-redis
    volumes:
      - docker-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  docker-data:
