version: '3'

services:
  url-dryer:
    build: .
    container_name: url-dryer
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - redis

  redis:
    image: redis
    container_name: url-dryer-redis
    volumes:
      - docker-data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  docker-data:
